---
- name: Install Packages | apt
  apt:
    state: latest
    pkg: "{{ item }}"
  with_items:
    - libsodium13
    - libsodium-dev
  tags:
    - software-installation
    - using-apt
    - libsodium
